### ISSUE TITLE
Is pods-compose obsolete nowadays?

### ISSUE THREAD

**Issue by fyrak1s** [abalage/pods-compose#5]
Hi greetings!
I had been using `pods-compose` a long while ago, but recently I started to use [podman-compose](https://github.com/containers/podman-compose). It seems this is now the "offical" replacement for `docker-compose`.

I would like to ask if `podman-compose` makes `pods-compose` basically obsolete nowadays, or are there some features that still set pods-compose apart in a good way, to use it over podman-compose?

I do not see a comparison to podman-compose in the readme.

Thank you :)

**Comment by abalage** [comment]
I consider `pods-compose` obsolete and I do not even use it myself anymore.

The biggest pain point is that it makes you to write shell scripts to describe containers, networks. Which you probably already have for docker-compose. It is tedious. 
Should you want to migrate to k8s for example then you have to start it again from scratch.

In production I rather use Ansible with some [abstraction of deployments](https://github.com/abalage/ansible_collection_elasticstack_podman/blob/main/roles/elasticsearch/tasks/elastic_stack_podman.yml). Such abstraction can be Kubernetes manifest files or even the docker-compose.yml files themselves.

I am sorry to say this about my pet project, but you are better to go with `podman-compose` or with some automation tool. :)

**Comment by fyrak1s** [comment]
Nice thanks for the hint with ansible and thank you for having provided pods-compose when there was no other alternative! :)

Maybe you should consider archiving this repo to reflect the status (and to not misguide new podman users:D)

Have a good day!

**Comment by abalage** [comment]
Yeah, good idea. Thanks :)
